### ISSUE TITLE
Create download dialog

### ISSUE THREAD

**Issue by Steditor** [brickify/brickify#382]
Idea of Stefanie:

Instead of trying to put everything in the sidebar, we could open a modal window, that
 - [x] provides the stud test-stripe (#234), especially for first-time users
 - [x] provides the 3d-print download with different stud sizes (#381)
 - [ ] provides the lego download instructions (#247)
 - [ ] provides sharing functionality (#311)
 - [ ] provides save/load buttons (?, maybe in main UI?)

![2015-03-20 download modeal window](https://cloud.githubusercontent.com/assets/236678/6896898/0aa24d58-d6f0-11e4-83cd-7994745c6360.jpg)

**Comment by Steditor** [comment]
Replaced by #608
